blog/urls.py
from django.urls import path
from .views import post_list_published, post_create, post_detail, post_update, post_delete, like,post_list_all, post_list_draft

app_name = "blog"
urlpatterns = [

    path("",post_list_all, name="list_all"),
    path("published",post_list_published, name="list_published"),
    path("draft",post_list_draft, name="list_draft"),
    path("create/",post_create, name="create"),
    path("<str:slug>/",post_detail, name="detail"),
    path("<str:slug>/update/",post_update, name="update"),
    path("<str:slug>/delete/",post_delete, name="delete"),
    path("<str:slug>/like/",like, name="like"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
        integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous" />

    {% comment %}
    <link rel="stylesheet" href=" {% static 'blog/css/bootstrap.min.css' %}" />
    {% endcomment %}



    <title>Django Auth Extending User</title>


</head>

<body>
    {% include "navbar.html" %}
    <div style="margin-top: 100px; margin-bottom: 100px" class="container">

        {% if messages %}
        {% for message in messages %}
        {% if message.tags == "error" %}
        <div class="alert alert-danger">{{ message }}</div>
        {% else %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
        {% endfor %}
        {% endif %}
        <!-- <div style="border: 1px solid rgba(128, 128, 128,.3);border-radius: 4px"  class="mx-3 my-0 p-3"> -->
        {% block content %}
        {% endblock content %}
        <!-- </div> -->
    </div>
    <script src="https://kit.fontawesome.com/8c29faa18e.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/timeout.js' %}"></script>
 

</body>

</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-toggleable-sm navbar-inverse fixed-top px-5" style="background-color: #5F788A;">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'blog:list_all' %}">Cem Blog</a>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">

                <a class="nav-link" href="{% url 'blog:list_all' %}">Home</a>
            </li>
            {% if request.user.is_superuser %}

            <li class="nav-item active">

                <a class="nav-link" href="{% url 'blog:list_published' %}">Published</a>
            </li>
            <li class="nav-item active">

                <a class="nav-link" href="{% url 'blog:list_draft' %}">Drafts</a>

            {% endif %}

            <li class="nav-item active">
                <a class="nav-link" href="https://github.com/cemispirli" target="_blank" rel="noopener">About</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:create' %}">New Post</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link"
                href = "{% url 'profile' %}">
                Profile
            </a>
            </li>
            {% if request.user.is_superuser %}
            <li class="nav-item active">
                <a class="nav-link"
                href = "{% url 'user_list' %}">
                Users List
            </a>
            </li>
            {% endif %}

            <li class="nav-item active">
              {% comment %} {% url 'logout' %} {% endcomment %}
              <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
            {% else %}

            <li class="nav-item active">
                {% comment %} {% url 'register' %} {% endcomment %}
                <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            <li class="nav-item active">
                {% comment %} {% url 'login' %} {% endcomment %}
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>